### ISSUE TITLE
[Workspace] Orchestrator

### ISSUE THREAD

**Issue by MikeSquall** [capsulajs/capsulajs#13]
## General description
The `Orchestrator` service is responsible for creating flows between the different services we have in the `Workspace`.
An `Orchestrator` defines the logic behavior of an application by creating specific interactions between the available services.

#### Prerequisites
N/A

#### Design description
The `Orchestrator` will have a configuration which contain a list of `flows`. 
A `flow` is an `Object` containing 3 properties: `name`, `id` and `flow`.
```typescript
interface Flow {
    name: string;
    id: string;
    flow(): // what to return ???
}
```

It exposes an `init` function which will run all the flows in the configuration.
```typescript
interface Orchestrator {
    init(initRequest: InitRequest): Promise<void>
}

interface InitRequest {}
```

- [ ] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Consideration
List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?

- [ ] Does the suggested changes are specific to some devices/browsers/environments

- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.
