### ISSUE TITLE
[ Workspace - Custom ] Selector Service

### ISSUE THREAD

**Issue by MikeSquall** [capsulajs/capsulajs#14]
## General description
The `Selector` service is a custom service which allow to deal with stream of data and to select a specific set of data

#### Prerequisites
- [RxJS](https://www.npmjs.com/package/rxjs)

#### Design description

The `Selector` will exposes 4 methods
```typescript
interface SelectorInterface<T extends K, K> {
  input(inputRequest: InputRequest<T>): Promise<void>;
  output$(outputRequest: OutputRequest): Observable<T[]>;
  select(selectRequest: SelectRequest<K>): Promise<T>;
  selected$(selectedRequest: SelectedRequest): Observable<T>;
}

interface InputRequest<T> {
  items$: Observable<T[]>;
}

interface OutputRequest {}

interface SelectRequest<K> {
  key: K;
}

interface SelectedRequest {}
```
| method      | purpose                                                        |
|----------------|----------------------------------------------------------|
|`input`         | allows to load items in the `Selector`           |
|`output$`     | allows to access the loaded items               |
|`select`       | allows to select an item                                |
|`selected$` | allows to access the selected item               |

- [ ] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Consideration

```gherkin
Given An instance of Selector service
When I input items on it
Then I expect to be able to get those items as an output

Given An instance of Selector service
When I select an item
Then I expect to have this item as selected
```

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.

**Comment by idanilt** [comment]
```ts
// What are Key, Key? seem like typo - 1 it's can be twice, 2 you need to define Key (it's not "generic")
interface SelectorInterface<Item extends Key, Key> {
// "setItems", seem better 
  setItemsStream(setItemsStreamRequest: SetItemsStreamRequest<Item>): Promise<void>;
// are you sending all items in one emit?
  items$(itemsRequest: ItemsRequest): Observable<Item[]>;
// Why do I need `Promise<Item>;`? I just need acknowledge, now?
// <Key> why to I need generic?
  selectItem(selectItemRequest: SelectItemRequest<Key>): Promise<Item>;
}

// `Key` if items are array it should be number
interface SelectItemRequest<Key> {
  key: Key;
}

```
