### ISSUE TITLE
[Workspace - web component] Canvas

### ISSUE THREAD

**Issue by 95kach** [capsulajs/capsulajs#15]
## General description
Create a canvas web component and layout service that will integrate it with a workspace.

- [ ] Discuss and finalize layout API. 
- [ ] Wrap canvas into web component (basic example).
- [ ] Integrate layout service with canvas (get the layout from a workspace and map it by the layout service, render: with env-selector, method-catalog.

#### Prerequisites
[Canvas](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/canvas)
## API
[Canvas Example](https://github.com/capsulajs/capsulahub-ui/blob/develop/stories/Canvas.stories.js#L58)

```
// names of another components that available in canvas;
const type BuilderName = 'EvnSelector' | 'MethodCatalog' | 'Logger'; 
const type Orientation = 'horizontal' | 'vertical';

interface Builders {
  [builderId: BuilderName]: (metadata: any) => React.Component;
}

interface Element {
  id: string;
  type: 'element';
  flex: number;
  tabIndex: number;
  tabs: Tab[];
}

interface Container {
  id: string;
  type: 'container';
  flex: number;
  orientation: Orientation;
  nodes: [<Container | Element>, <Container | Element>]
}

interface Tab {
  id: string;
  name: string;
  builderId: BuilderName;
  metadata: any;
}

const type Layout = Container | Element;

interface CanvasProps {
  builders: Builders;
  layout: Layout;
  onUpdate: (newLayout: Layout) => void;
  width: number;
  height: number;
}
```
#### Design description

A clear and concise description of the design proposition.

- [ ] Is it backward compatible ?
- [x] Adds new API
- [x] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

#### Consideration
List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?

- [ ] Does the suggested changes are specific to some devices/browsers/environments

- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.
