### ISSUE TITLE
[Workspace - web Component] Logger

### ISSUE THREAD

**Issue by 95kach** [capsulajs/capsulajs#16]
## General description
Need to wrap [Logger from here](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/logger) into the new web component to use it in the workspace.
#### Prerequisites
Capsulahub-UI: [Logger](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/logger) 
## API
```
type Type = 'request' | 'response';
interface Event {
  timestamp: number;
  correlationId: string;
  type: Type;
  serviceName: string;
  methodName: string;
  request: any;
  response: any;
}

interface {
  logs: <Observable<Event>>[];
  width: number;
  height: number;
}
```
#### Design description

A clear and concise description of the design proposition.

- [ ] Is it backward compatible ?
- [ ] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

#### Consideration
List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?

- [ ] Does the suggested changes are specific to some devices/browsers/environments

- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases

```	
 Scenario: Events are logged (check the format)	
     Given  Logger web component
     When  Logger is initialized
     Then   at each polling interval of X seconds an event is logged
     And    each log has the correct model
		   |property       |type   |
		   |timestamp    | number|
		   |type              |'request'/'response'|
		   |serviceName |string|
		   |methodName|string|
// need to confirm the final model

 Scenario: Check delete cross to remove all logs
     Given  Logger web component
     And    Logger is initialized
     When  click on the delete cross  
     Then   all recorded logs are removed
     And    logs continue to be recorded at each polling interval of X seconds

 Scenario: Check arrows icon color to correspond to the event type
     Given  Logger web component
     And    Logger is initialized
     When  some logs are recorded
     Then   the arrows icon have the correspondent color 
		   |type of event|color|
		   |response      |green|
		   |request        |red  |

 Scenario: Hovering on the dot near to log will change the color of all the dots of the logs with the same service/method name
     Given Logger web component
     And    Logger is initialized
     And    some logs are recorded
     When  hover on the dot near to log
     Then   the dot is changing its color
     And    all the dots near to logs with the same service/method name are changing its color		   
 ```

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.

**Comment by 95kach** [comment]
@stephanebenayoun I have a few questions)
1. Where I should get `correlationId`?
2. Do we need to render `request`? Because in the design I see only one JSON object that can be opened, and as I understood it's a `request` but logger Event event also have `request` what to do with `request`?
3. In the design, we have green/red arrows and in which case we should show them instead of the default color?
