### ISSUE TITLE
[Workspace - web component] Request Form

### ISSUE THREAD

**Issue by 95kach** [capsulajs/capsulajs#17]
## General description
Need to wrap [Request Form from here](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/request-form) into the new web component to use it in the workspace.
#### Prerequisites
Capsulahub-UI: [Request Form](https://github.com/capsulajs/capsulahub-ui/tree/develop/src/components/request-form)
## API
```
interface SubmitRequest {
  language: string;
  arguments: string[];
}

interface RequestFormProps {
  submit: (response: SubmitResponse) => void; // callback on submit
  setArgument: (index: number, argument: string) => void; // callback on argument changed
  selectLanguage: (language: string) => void; // callback on language changed
  input: string;
  path: string;
  width: number;
  height: number;
}

interface RequestFormState {
    language: string; //  'javascript',
    arguments: string[];  // ['{}', '{a: 2}']
    isValid: boolean;
}
```
#### Design description

A clear and concise description of the design proposition.

- [ ] Is it backward compatible ?
- [ ] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

#### Consideration
List of everything to consider before writing test cases.

- [ ] Does the suggested changes impact the current behaviour ?

- [ ] Does the suggested changes are specific to some devices/browsers/environments

- [ ] Does the suggested changes require to add new dependencies to the package ?

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

## Key Performance Indicator (KPI) Definition

A clear target that can be measured by the change.

_**Example:** reduce bundle size by X%._

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.
