### ISSUE TITLE
[Workspace - Core] Workspace service

### ISSUE THREAD

**Issue by stephanebenayoun** [capsulajs/capsulajs#18]
## General description
Workspace is the main core service of CapsulaHub. Workspace service is responsible for loading the CapsulaHub elements (services and components) and for letting them to communicate together.
The Workspace has to be initialised with a token that will be used to get its own configuration and that can be also used by elements to get their own configuration.
The Workspace configuration will include the workspace name and a list of services. Each service will be described by its name, displayed name, the path to import it and eventually some options.

#### Prerequisites
None.

#### Design description

```typescript
interface Workspace {
  start(startRequest: StartRequest): Promise<void>;
  services(servicesRequest: ServicesRequest): Promise<ServicesMap>;
  components(componentsRequest: ComponentsRequest): Promise<ComponentsMap>;
  registerService(registerServiceRequest: RegisterServiceRequest): Promise<void>;
  registerComponent(registerComponentRequest: RegisterComponentRequest): Promise<void>;
}

```
- [ ] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Changes
New API.

#### Consideration
```gherkin
Given Workspace service instantiated with token 123
And Configuration for token 123 that includes service A and B and components 1 and 2
When I run workspace start method
And I call workspace services method
Then I expect to receive service A and B
```
```gherkin
Given Workspace service instantiated with token 123
And Configuration for token 123 that includes service A and B and components 1 and 2
When I run workspace start method
And I call workspace components method
Then I expect to receive components 1 and 2
```

## Test cases

Link to the PR with test cases, that are written in _**[Gherkin Syntax](https://docs.cucumber.io/gherkin/reference/)**_ and cover all the possible scenarios.

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Product owner
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes
- [ ] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.

**Comment by stephanebenayoun** [comment]
Workspace should also expose to each service its configuration, we need to define the API for it.
