### ISSUE TITLE
JS containers - MVP

### ISSUE THREAD

**Issue by idanilt** [capsulajs/capsulajs#33]
## Proposition

Create working JS Containers based on research #5 #10 

1. create a js file (you can call it what ever you want, it recommend to call it {name}.js)
2. config your capsula container env
myApp.js
```ts
import { 
    name, 
    images, 
    exposeEvents,
    listenEvents,
    // window, document any other native api // TBD 
} from 'capsula';
import myLib './src/myRoot/file';
// use import('./src/myRoot/file'); for lazy load / conditinal loading

name("myApp");
images("react@1.0.0", "rxjs", "mylib");

exposeEvents(eventListener, eventListener ...); /// listener from module you want to expose outside
listenEvents(eventListener, eventListener ...); // listeners from outside to connect container

export myLib; // if other images depend on it, you need to export it
```
**notice**   
You don't have to put your dependencies as an image.
Capsula will import it from your node_modules, if you put it in `images()` you must create image.

3. run capsula build
> ```bash capsula build [capsula]```

this will create
dist/capsula/    
├── capsula.js   
├── chunks/   
│   ├── d131dd02c5e6eec4.js   
│   ├── 693d9a0698aff95c.js   
│   ├── 2fcab58712467eab.js   
│   └── 55ad340609f4b302.js  
├── images/  
│   └── imageName  
│       └── version  
│           └── bootstrap.js  
├── alias/  
|   ├── react.js  
|   └── react@1.0.0.js  
└── internal  

**notice**   
Capsula images design to be merged. If you have monorepo, you can write all packages images to the same directory.
If you are deploying it to cdn you can just drop the files, you shouldn't clean it.    
    
4. import capsula and call capsula to run a container
```ts 
import { capsula } from "./capsula/capsula.js";

capsula({
    process="this": Container|"this"|"worker"|"sharedWorker" , 
    name:string, 
    version:string, 
    env:any
}): Container
```
**notice** You can start a container with 1 image and then add additional image to it by calling this function again with the Container instance return by previews call. If you put "this" it will run the image on the container on the current process
**notice** if you want to 100% decoupling use process=worker

> ```bash capsula start [capsula]```
Capsula start will start or connect to existing capsula server
Then it will watch the current "capsula" and post update when it done
Capsula server always start from the last state. It will save the time of building from scratch on each iteration. Capsula server will stay active as long there is at least 1 `capsula start` listening to the server 

### Goals/Values

- Effective way to manage, package and ship JS, with multi team support, delta shipment, share dependencies and canary release builtin
- Control & manage the environment, run in predictable environment, isolation, orchestrate interactions between containers

### RoadMap

- [ ] Init capsulajs/capsulajs repo with Lerna CI / CD + standards (linting etc) #34 *[4d]*
- [ ] Implement HFS, hash base ESM JS file system https://github.com/capsulajs/capsulajs/issues/36
- [ ] Create an image https://github.com/capsulajs/capsulajs/issues/37 *[10d]*
- [ ] Create `capsula build` command, create image from your files #35  *[4d]*
- [ ] Impl container.run (start an image on container) https://github.com/capsulajs/capsulajs/issues/38 *[10d]*
- [ ] Create capsula server, development server to support local development *[10d]*

### Definition of Done

- [x] Relevant issues have been created
